### ISSUE TITLE
Patching zombie villager sieges to not spawn zombies directly on the player

### ISSUE THREAD

**Issue by eggyplantsu** [embeddedt/ArchaicFix#100]
https://bugs.mojang.com/browse/MC-7488
Fixes zombie spawning behavior to spawn outside near the village's radius instead.
I tried implementing this as a standalone mod for gtnh after dying to a zombie siege spawning directly on me, but realizing 1.7.10 was barely supported and with no way to access deobfuscated 1.7.10. I decided post this as an enhancement.

**Comment by DrParadox7** [comment]
@eggyplantsu this is already addressed in BugTorch:
https://github.com/jss2a98aj/BugTorch/blob/87ced841b2550f8148966c043d83c37118b2306f/src/main/java/jss/bugtorch/mixins/early/minecraft/fix/MixinVillageSiege.java#L61

No need for ArchaicFix to implement it too since they are both compatible with one another and are recommended.
