### ISSUE TITLE
[1.7.10] Archaicfix crash when installed on crucibleMC (plugins + mods server)

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#34]
https://github.com/CrucibleMC/Crucible

Mods list : 

00gasstation-mc1.7.10-0.3.0
archaicfix-mc1.7.10-0.3.0-16-g059b8b4
falsepatternlib-mc1.7.10-0.10.10

logs : no logs

**Comment by embeddedt** [comment]
Crucible/Thermos/etc. are not supported.

**Comment by quentin452** [comment]
ok

**Comment by Zilacon** [comment]
Couldn't incompatible features be disabled once bukkit/spigot is detected like what other mods do?
As far as i see its the FalsePatternLib thats causing the incompatibilities not ArchaicFix itself.
I could be wrong, but just my observations.
Pretty much every server in existence uses thermos or crucible as spongeforge doesn't exist for 1.7.10 and there really isn't a modded 'plugin' eco system for 1.7.10 or lower versions.

I'm not asking for complete feature compatibility, but simply disable the things that aren't compatible with the server if it isn't possible to make them compatible.

Any form of support would be appreciated.

**Comment by embeddedt** [comment]
The issue is that Crucible/Thermos/etc are not using pure Forge, but rather a modified implementation that still exposes the standard Forge APIs. This is okay for regular mods that only need Forge, but mods that modify Minecraft directly are expecting to be patching the original Forge implementation, not Crucible's modified version. The only way to properly support this would be to have separate patches where needed for Crucible.
