### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by iamsoNewBee** [embeddedt/ArchaicFix#42]
[minecraft-exported-crash-info-2022-10-04T16-44-52.zip](https://github.com/embeddedt/ArchaicFix/files/9704225/minecraft-exported-crash-info-2022-10-04T16-44-52.zip)

**Comment by iamsoNewBee** [comment]
maybe DAPI?

**Comment by makamys** [comment]
```
[16:43:19] [main/INFO]: Adding library it.unimi.dsi:fastutil:8.5.8, requested by mod archaicfix
[16:43:19] [main/INFO]: Release: repo.maven.apache.org:-1
[16:43:19] [main/INFO]: Check: repo.maven.apache.org:443
[16:43:19] [main/INFO]: Redirect: repo.maven.apache.org -> 0.0.0.0
```
The issue is caused by NonUpdate preventing connection to the Internet, which makes fastutil fail to get downloaded. You can try adding `repo.maven.apache.org` or `apache.org` to its whitelist (`nu-whitelist.txt`), but I'd recommend just getting rid of the mod entirely, since it's likely to cause other similar issues in the future.

**Comment by iamsoNewBee** [comment]
okay i will have a try

**Comment by makamys** [comment]
> by the way ,can i close DAPI`S annoying notification by this？XD

Not sure. NonUpdate *should* accomplish that without any additional configuration, but I haven't tried if it actually does.

**Comment by iamsoNewBee** [comment]
i have solved this by enable"#only solve main threat".
