### ISSUE TITLE
[1.7.10] Vampirism crash on startup when archaicfix is installed

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#46]
descriptions :
Crash on startup when archaicfix and vampirism is installed

mods lists :

Vampirism-1.7.10-0.7.9
00gasstation-mc1.7.10-0.3.5
archaicfix-mc1.7.10-0.3.3
falsepatternlib-mc1.7.10-0.10.13

crash report:

[crash-2022-10-11_07.31.16-client.txt](https://github.com/embeddedt/ArchaicFix/files/9751410/crash-2022-10-11_07.31.16-client.txt)

**Comment by makamys** [comment]
This looks like a FalsePatternLib issue to me, not an ArchaicFix issue.

It looks like Vamprisim has a class like this:
```java
public class BlockList {
   public Block block;
   public String blockId;
   private final int[] meta;
   private List<BlockList.BlockPosition> blockPositions;
   // ...
}
```
And it tries to deserialize it using Gson. It fails because FalsePatternLib's `MutableBlockPos` class cannot be deserialized (`java.lang.IllegalArgumentException: class com.falsepattern.lib.compat.BlockPos$MutableBlockPos declares multiple JSON fields named x`).

By the way, I can't reproduce your crash, using the same mods, with the default configs. I get a different one (a StackOverflowError of indeterminate origin), but it also involves Gson.
[crash-2022-10-11_15.29.58-client.txt](https://github.com/embeddedt/ArchaicFix/files/9756319/crash-2022-10-11_15.29.58-client.txt)
