### ISSUE TITLE
Invisible bug when i put a mekanism cable next to a torch

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#52]
Archaicfix enabled

![Capture d’écran_2022-10-29_01-14-37](https://user-images.githubusercontent.com/42176772/198749337-57a36b8e-e673-4a85-91a4-bbf5ba5316ca.png)

Archaicfix disabled

![Capture d’écran_2022-10-29_01-15-03](https://user-images.githubusercontent.com/42176772/198749338-536bb39c-6326-42af-afbd-a5e67826f23f.png)

**Comment by quentin452** [comment]
fixed by disabling disableBlockingChunkUpdates in archaicfix

**Comment by embeddedt** [comment]
@makamys Any idea why threaded chunk updates would cause this? I'm not sure.

**Comment by makamys** [comment]
Mekanism is probably doing something weird to render multiple blocks inside the same block. I'm going to revisit the issues of the occlusion tweak and the threaded chunk updating in the near future, I'll have a proper look then.

**Comment by makamys** [comment]
It happened because ForgeMultiPart nests block models. The torch block gets drawn as a "child" of the FMP block. Since it's a vanilla block, its rendering got skipped on the main thread. But of course, the render thread never rendered it either since it's part of a modded block.

To fix this, I made child models (which should only exist as parts of modded blocks) always get rendered on the main thread.
