### ISSUE TITLE
Crash with modpack

### ISSUE THREAD

**Issue by Starexify** [embeddedt/ArchaicFix#79]
ArchaicFix crash with modpack, I don't know the cause yet because I am not that good at reading crash reports and logs but It looks like it's from a class?

Crash Report: https://pastebin.com/v96n6e1j
Log: https://pastebin.com/G7vcPCgR

**Comment by reuben-matus** [comment]
I got the same problem, I looked through the code and I think it's an issue in 'src/main/java/org/embeddedt/archaicfix/recipe/IFasterCraftingManager.java' (IFasterCraftingManager) because the mod maker tried to cast the default minecraft crafting manager to this and it's an interface class which means it's like an incomplete class that has methods that aren't defined

**Comment by embeddedt** [comment]
Looks like you do not have GTNHMixins or UniMixins installed. As of the
latest version you need one of them (I recommend the latter).
